#!/bin/bash

echo "🔧 Google Cloud Console Setup Guide"
echo "=================================="
echo ""
echo "Follow these steps to fix the 'Access blocked' error:"
echo ""
echo "1. 🌐 Go to Google Cloud Console"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. 📋 Select your project (or create a new one)"
echo ""
echo "3. 🔌 Enable Google Calendar API:"
echo "   - Go to 'APIs & Services' → 'Library'"
echo "   - Search for 'Google Calendar API'"
echo "   - Click on it and press 'ENABLE'"
echo ""
echo "4. 🔑 Configure OAuth Consent Screen:"
echo "   - Go to 'APIs & Services' → 'OAuth consent screen'"
echo "   - Choose 'External' user type"
echo "   - Fill in required fields:"
echo "     • App name: Your App Name"
echo "     • User support email: your-email@example.com"
echo "     • Developer contact: your-email@example.com"
echo "   - Click 'Save and Continue'"
echo ""
echo "5. 🎯 Add OAuth Scopes (IMPORTANT):"
echo "   - In OAuth consent screen, go to 'Scopes' tab"
echo "   - Click 'Add or Remove Scopes'"
echo "   - Search and add these scopes:"
echo "     ✓ ../auth/calendar"
echo "     ✓ ../auth/userinfo.email"
echo "     ✓ ../auth/userinfo.profile"
echo "   - Click 'Update' then 'Save and Continue'"
echo ""
echo "6. 🔐 Configure OAuth Credentials:"
echo "   - Go to 'APIs & Services' → 'Credentials'"
echo "   - Click 'Create Credentials' → 'OAuth 2.0 Client ID'"
echo "   - Application type: 'Web application'"
echo "   - Add this redirect URI:"
echo "     http://localhost:3001/auth/google/callback"
echo "   - Copy the Client ID and Client Secret"
echo ""
echo "7. 🧪 Add Test Users (for development):"
echo "   - Back in OAuth consent screen, go to 'Test users'"
echo "   - Add your Google email address as a test user"
echo "   - This allows you to test the app during development"
echo ""
echo "8. ✅ Update your .env file with the new credentials"
echo ""
echo "🚨 Common Issues:"
echo "   • Make sure you're using the same Google account for testing"
echo "   • Verify the redirect URI matches exactly"
echo "   • Ensure all required scopes are added"
echo "   • Add yourself as a test user"

echo ""
echo "📞 Need help? The setup process can be tricky!"
echo "Let me know if you get stuck on any step."
